FROM node:20-alpine
WORKDIR /app

# 1 - Variable d'evt
ENV NODE_ENV=production

# 2 - Manifestes
COPY package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund

# 3 - Le reste du code
COPY . .

EXPOSE 3000
USER node
CMD ["node", "server.js"]